#!/usr/bin/env php
<?php

use Stoffel\Console\Gradient\GradientHelper;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\SingleCommandApplication;

require dirname(__DIR__).'/vendor/autoload.php';

(new SingleCommandApplication())
    ->setCode(function (InputInterface $input, OutputInterface $output) {

        $builtIn = [
            'cristal',
            'teen',
            'mind',
            'morning',
            'vice',
            'passion',
            'fruit',
            'instagram',
            'atlas',
            'retro',
            'summer',
            'pastel',
            'rainbow',
        ];

        $output->write(PHP_EOL);
        foreach($builtIn as $gradient) {
            $output->write('  '.str_pad($gradient, 12));

            GradientHelper::create($output)
                ->setText(str_repeat('■', 48))
                ->setStyle($gradient)
                ->write();
        }
        $output->write(PHP_EOL);

    })
    ->run();

